In [0]:
import numpy as np
import torch
import torch.nn as nn

In [0]:
# Input (Temperature, Rainfall, Humidity)
inputs = np.array([[73,67,43], [91,88,64], [87,134,58],
                   [102,43,37], [69,96,70], [73,67,43],
                   [91,88,64], [87,134,58], [102,43,37],
                   [69,96,70], [73,67,43], [91,88,64],
                   [87,134,58], [102,43,37], [69,96,70]],
                  dtype='float32')

# Target (Apples,Orange)
target = np.array([[56,70], [81,101], [119,133],
                   [22,37], [103,119], [56,70],
                   [81,101], [119,133], [22,37],
                   [103,119], [56,70], [81,101],
                   [119,133], [22,37], [103,119]],
                  dtype='float32')

inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

In [0]:
from torch.utils.data import TensorDataset

In [11]:
train_ds = TensorDataset(inputs, target)
train_ds[::]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [0]:
from torch.utils.data import DataLoader

In [0]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size, shuffle=True)

In [14]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 91.,  88.,  64.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [ 81., 101.],
        [ 81., 101.],
        [119., 133.]])


In [16]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5158,  0.4959, -0.0154],
        [ 0.2588, -0.5266, -0.4025]], requires_grad=True)
Parameter containing:
tensor([0.1000, 0.4655], requires_grad=True)


In [17]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5158,  0.4959, -0.0154],
         [ 0.2588, -0.5266, -0.4025]], requires_grad=True),
 Parameter containing:
 tensor([0.1000, 0.4655], requires_grad=True)]

In [18]:
predect = model(inputs)
predect

tensor([[ 70.3134, -33.2303],
        [ 89.6877, -48.0821],
        [110.5261, -70.9249],
        [ 73.4626, -10.6732],
        [ 82.2152, -60.4026],
        [ 70.3134, -33.2303],
        [ 89.6877, -48.0821],
        [110.5261, -70.9249],
        [ 73.4626, -10.6732],
        [ 82.2152, -60.4026],
        [ 70.3134, -33.2303],
        [ 89.6877, -48.0821],
        [110.5261, -70.9249],
        [ 73.4626, -10.6732],
        [ 82.2152, -60.4026]], grad_fn=<AddmmBackward>)

In [0]:
import torch.nn.functional as F

In [0]:
loss_fn = F.mse_loss

In [21]:
loss = loss_fn(model(inputs),target)
print(loss)

tensor(11235.7910, grad_fn=<MseLossBackward>)


In [0]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [0]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
  
  #Repeat for given number of epochs
  for epoch in range(num_epochs):
    
    #Train with batches of data
    for xb,yb in train_dl:

      # 1. Generate predictions
      pred = model(xb)

      # 2. Calculate loss
      loss = loss_fn(pred, yb)

      # 3. Compute gradients
      loss.backward()

      # 4. Update parameter using gradients
      opt.step()

      # 5. Reset the gradients to zero 
      opt.zero_grad()

    # Print the progress
    if (epoch+1) % 10 == 0:
      print("Epoch [{}/{}], Loss: {:,.4f}".format(epoch+1, num_epochs, loss.item()))

In [29]:
fit(130, model, loss_fn, opt)

Epoch [10/130], Loss: 18.2604
Epoch [20/130], Loss: 25.0675
Epoch [30/130], Loss: 25.4676
Epoch [40/130], Loss: 18.8794
Epoch [50/130], Loss: 17.8878
Epoch [60/130], Loss: 9.7283
Epoch [70/130], Loss: 8.6670
Epoch [80/130], Loss: 13.6883
Epoch [90/130], Loss: 11.0214
Epoch [100/130], Loss: 25.2273
Epoch [110/130], Loss: 17.4987
Epoch [120/130], Loss: 11.4668
Epoch [130/130], Loss: 11.0753


In [30]:
preds = model(inputs)
preds

tensor([[ 57.3219,  70.5689],
        [ 79.9712,  98.0022],
        [122.7033, 137.6890],
        [ 22.3170,  38.5160],
        [ 97.3885, 113.7795],
        [ 57.3219,  70.5689],
        [ 79.9712,  98.0022],
        [122.7033, 137.6890],
        [ 22.3170,  38.5160],
        [ 97.3885, 113.7795],
        [ 57.3219,  70.5689],
        [ 79.9712,  98.0022],
        [122.7033, 137.6890],
        [ 22.3170,  38.5160],
        [ 97.3885, 113.7795]], grad_fn=<AddmmBackward>)

In [31]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])